---
name: ci
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

env:
  MIX_ENV: test
  otp-version: '24'
  elixir-version: '1.12'
  cache-version: '0'

jobs:
  build:
    strategy:
      matrix:
        otp: ['22.3.4.21', '23.3.4.7', '24']
        elixir: ['1.10.4', '1.11.4', '1.12']
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}
      - name: restore-deps
        uses: actions/cache@v1
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ matrix.otp }}-${{ matrix.elixir }}-${{ env.cache-version }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - name: restore-build
        uses: actions/cache@v1
        with:
          path: _build
          key: ${{ runner.os }}-build-${{ matrix.otp }}-${{ matrix.elixir }}-${{ env.cache-version }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - name: deps.get
        run: mix deps.get
      - name: compile
        run: | 
          git fetch --tags
          mix compile --warnings-as-errors

  format:
    name: Format
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.otp-version }}
          elixir-version: ${{ env.elixir-version }}
      - name: restore-deps
        uses: actions/cache@v1
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ env.otp-version }}-${ env.elixir-version }}-${{ env.cache-version }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - name: restore-build
        uses: actions/cache@v1
        with:
          path: _build
          key: ${{ runner.os }}-build-${{ env.otp-version }}-${{ env.elixir-version }}-${{ env.cache-version }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - name: format
        run: |
          git fetch --tags
          mix format --check-formatted

  dialyzer:
    needs: build
    strategy:
      matrix:
        otp: ['22.3.4.21', '23.3.4.7', '24']
        elixir: ['1.10.4', '1.11.4', '1.12']
    name: Dialyzer
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}
      - name: restore-deps
        uses: actions/cache@v1
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ matrix.otp }}-${{ matrix.elixir }}-${{ env.cache-version }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - name: restore-build
        uses: actions/cache@v1
        with:
          path: _build
          key: ${{ runner.os }}-build-${{ matrix.otp }}-${{ matrix.elixir }}-${{ env.cache-version }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - name: restore-plts
        uses: actions/cache@v1
        with:
          path: priv/plts
          key: ${{ runner.os }}-mllp-dialyzer-${{ matrix.otp }}-${{ matrix.elixir }}-${{ env.cache-version }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - name: dialyze
        run: |
          git fetch --tags
          mix dialyzer

  test:
    needs: build
    strategy:
      matrix:
        otp: ['22.3.4.21', '23.3.4.7', '24']
        elixir: ['1.10.4', '1.11.4', '1.12']
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}
      - name: restore-deps
        uses: actions/cache@v1
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ matrix.otp }}-${{ matrix.elixir }}-${{ env.cache-version }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - name: restore-build
        uses: actions/cache@v1
        with:
          path: _build
          key: ${{ runner.os }}-build-${{ matrix.otp }}-${{ matrix.elixir }}-${{ env.cache-version }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - name: test
        run: |
          git fetch --tags
          mix coveralls

  release:
    needs: [build, format, test, dialyzer]
    name: Bump version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
